[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Content-Security-Policy = "default-src 'self' https://farhatmunib.com; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data: https:;"

[[headers]]
  for = "/images/*"
    Content-Type = "image/webp"

# Domain settings
[[redirects]]
  from = "https://farhatmunib.netlify.app/*"
  to = "https://farhatmunib.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://farhatmunib.com/*"
  to = "https://farhatmunib.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  compress = true

[build.processing]
  skip_processing = true
